name: Build, Test, Tag and Package

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test -- --passWithNoTests

    tag-and-package:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get latest tag
              id: get_latest_tag
              run: |
                  latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
                    major=$(echo "$latest_tag" | cut -d. -f1 | sed 's/v//')
                    minor=$(echo "$latest_tag" | cut -d. -f2)
                    patch=$(echo "$latest_tag" | cut -d. -f3)

                    if [ $patch -lt 10 ]; then
                      new_tag="v${major}.${minor}.$((patch + 1))"
                    elif [ $minor -lt 10 ]; then
                      new_tag="v${major}.$((minor + 1)).0"
                    else
                      new_tag="v$((major + 1)).0.0"
                    fi
                  fi
                  echo "::set-output name=tag::$new_tag"

            - name: Create and push tag
              if: success()
              run: |
                  git tag ${{ steps.get_latest_tag.outputs.tag }}
                  git push origin ${{ steps.get_latest_tag.outputs.tag }} --quiet --follow-tags

            - name: Build and Publish Package
              run: |
                  npm install
                  npm run build
                  npm publish
