name: Build, Test, Tag and Package

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test -- --passWithNoTests

    tag-and-package:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get latest tag
              id: get_latest_tag
              run: |
                  current_tag=$(git describe --abbrev=0 --tags)  # Obtém a última tag
                  major=$(echo $current_tag | cut -d. -f1 | sed 's/v//')  # Extrai a parte principal da versão
                  minor=$(echo $current_tag | cut -d. -f2)  # Extrai a parte secundária da versão
                  patch=$(echo $current_tag | cut -d. -f3 | sed 's/v//')  # Extrai a parte de revisão da versão

                  # Incrementa o patch
                  next_patch=$((patch + 1))

                  # Cria a nova tag
                  new_tag="v$major.$minor.$next_patch"

                  echo "::set-output name=new_tag::$new_tag"

            - name: Create and push tag
              if: success()
              run: |
                  git tag ${{ steps.get_latest_tag.outputs.tag }}
                  git push origin ${{ steps.get_latest_tag.outputs.tag }} --quiet --follow-tags

            - name: Build and Publish Package
              run: |
                  npm install
                  npm run build
                  npm publish
