name: Create Tag and Package

on:
    push:
        branches:
            - master

jobs:
    tag-and-package:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Git
              run: |
                  git config --local user.email "your-email@example.com"
                  git config --local user.name "Your Name"

            - name: Get latest tag
              id: get_latest_tag
              run: |
                  latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
                  if [ -z "$latest_tag" ]; then
                    new_tag="v1.0.0"
                  else
                    new_tag="v$(echo "$latest_tag" | cut -d. -f1).$(($(echo "$latest_tag" | cut -d. -f2) + 1)).0"
                  fi
                  echo "::set-output name=tag::$new_tag"

            - name: Create and push tag
              if: success()
              run: |
                  git tag ${{ steps.get_latest_tag.outputs.tag }}
                  git push origin ${{ steps.get_latest_tag.outputs.tag }}

            - name: Build and Publish Package
              run: |
                  # Exemplo: Construir e publicar um pacote npm
                  npm install
                  npm run build
                  npm publish
