name: Create Tag and Package

on:
    push:
        branches:
            - master

jobs:
    tag-and-package:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get latest tag
              id: get_latest_tag
              run: |
                  latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
                  if [ -z "$latest_tag" ]; then
                    new_tag="v1.0.0"
                  else
                    new_tag="v$(echo "$latest_tag" | cut -d. -f1).$(($(echo "$latest_tag" | cut -d. -f2) + 1)).0"
                  fi
                  echo "::set-output name=tag::$new_tag"

            - name: Create and push tag
              if: success()
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const tag = process.env.INPUT_TAG;
                      const github = context.github;
                      await github.git.createRef({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        ref: `refs/tags/${tag}`,
                        sha: context.sha
                      });

            - name: Build and Publish Package
              run: |
                  npm install
                  npm run build
                  npm publish
