name: Build, Test, Tag and Package

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test -- --passWithNoTests

    incrementar-tag:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Obter Última Tag
              id: obter_tag
              run: |
                  latest_tag=$(git describe --abbrev=0 --tags)
                  echo "Última tag encontrada: $latest_tag"
                  export LATEST_TAG=$latest_tag

            - name: Calcular Próxima Versão
              id: calcular_versao
              run: |
                  # Extrai a parte numérica da última tag
                  last_version=${LATEST_TAG#v}
                  major=$(echo $last_version | cut -d. -f1)
                  minor=$(echo $last_version | cut -d. -f2)
                  patch=$(echo $last_version | cut -d. -f3)

                  # Obtém o número de commits desde a última tag
                  commits_count=$(git rev-list ${LATEST_TAG}..HEAD --count)

                  # Incrementa o patch
                  next_patch=$((patch + commits_count))

                  # Cria a nova versão
                  new_version="v$major.$minor.$next_patch"

                  echo "Nova versão calculada: $new_version"
                  echo "::set-output name=new_version::$new_version"

            - name: Criar e Empurrar Nova Tag
              if: ${{ github.event_name == 'push' && github.ref == 'refs/tags/v*' }}
              run: |
                  git tag ${{ steps.incrementar_tag.outputs.new_tag }}
                  git push origin ${{ steps.incrementar_tag.outputs.new_tag }}

            - name: Build and Publish Package
              run: |
                  npm install
                  npm run build
                  npm publish
