name: Auto Tag on Master Push

on:
    push:
        branches:
            - master

jobs:
    tag-and-package:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Determine next tag version
              id: determine_tag
              run: |
                  latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
                  if [ -z "$latest_tag" ]; then
                    new_tag="v1.0.0"
                  else
                    major=$(echo "$latest_tag" | cut -d. -f1)
                    minor=$(echo "$latest_tag" | cut -d. -f2)
                    patch=$(echo "$latest_tag" | cut -d. -f3)
                    new_tag="v$((major)).$((minor)).$((patch + 1))"
                  fi
                  echo "::set-output name=tag::$new_tag"

            - name: Create and push tag
              if: success()
              run: |
                  new_tag=${{ steps.determine_tag.outputs.tag }}
                  git tag $new_tag
                  git push origin $new_tag

            - name: Build and Publish Package
              run: |
                  npm install
                  npm run build
                  npm publish
