name: Publish package to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ltz-labs'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "operacao@ltzcapital.com.br"
          git config --global user.name "LTZ-CAPITAL"

      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.3.0
        with:
          major_pattern: "[RELEASE]"
          minor_pattern: "[FEAT]"
          version_format: "${major}.${minor}.${patch}-${increment}"

      - name: Update version
        run: npm version ${{ steps.versioning.outputs.version_tag }}

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
