name: Publish package to GitHub Packages

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14.x'

            - name: Install dependencies
              run: npm ci

            - name: Configure Git
              run: |
                  git config --global user.email "operacao@ltzcapital.com.br"
                  git config --global user.name "LTZ-CAPITAL"

            - name: Determine version increment
              id: version
              run: |
                  PREVIOUS_VERSION=$(npm show your-package-name version)

                  BRANCH_NAME=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
                  if [[ $BRANCH_NAME == *"release"* ]]; then
                    echo "major"
                  elif [[ $BRANCH_NAME == *"feature"* ]]; then
                    if [[ "$PREVIOUS_VERSION" == "10.0.0" ]]; then
                      echo "minor"
                    else
                      echo "patch"
                    fi
                  else
                    echo "patch"
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: Bump version
              run: npm version ${{ steps.version.outputs.version }}

            - name: Publish to GitHub Packages
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
