name: Publish package to GitHub Packages

on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@ltz-labs'
            - run: npm ci
            - name: Configure Git
              run: |
                  git config --global user.email "operacao@ltzcapital.com.br"
                  git config --global user.name "LTZ-CAPITAL"
            - name: Get Versioning Data
              id: versioning
              uses: Soumeh/Auto-Versioning@main
            - run: npm version ${{ steps.versioning.outputs.tag }}
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
