name: Publish package to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  setup-node:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ltz-labs'

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup-node

    steps:
      - name: Install dependencies
        run: npm ci

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Build project
        run: npm run build

  configure-git:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "operacao@ltzcapital.com.br"
          git config --global user.name "LTZ-CAPITAL"

  semantic-versioning:
    runs-on: ubuntu-latest
    needs: configure-git

    steps:
      - name: Semantic Versioning
        uses: paulhatch/semantic-version@v5.3.0
        id: versioning
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-${increment}"
          namespace: azure
          bump_each_commit: true

  update-version:
    runs-on: ubuntu-latest
    needs: semantic-versioning

    steps:
      - name: Update package version
        run: npm version ${{ steps.versioning.outputs.version_tag }}

  publish:
    runs-on: ubuntu-latest
    needs: update-version

    steps:
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
